development:
  adapter: mysql
  database: stoneboat_development
  encoding: utf8
  pool: 5
  username: stoneboat
  password: j0AnnA
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: stoneboat_test
  encoding: utf8
  pool: 5
  username: stoneboat
  password: j0AnnA
  socket: /tmp/mysql.sock
